<a href="https://colab.research.google.com/github/ppujari/PyTorch/blob/main/PyTorch_tips.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: pytorch tips

# Use `torch.cuda.is_available()` to check if CUDA is available before using it.
# This can help avoid errors and improve performance.

# Use `torch.no_grad()` context manager to disable gradient computation when it is not needed.
# This can save memory and improve performance.

# Use `torch.jit.trace()` to create a traced version of your model for improved performance.
# This can be especially useful for models that are used frequently.

# Use `torch.utils.data.DataLoader` to load your data in batches.
# This can help improve performance by reducing the number of times the data is loaded into memory.

# Use `torch.optim.lr_scheduler` to adjust the learning rate during training.
# This can help improve the convergence of the model.

# Use `torch.nn.utils.clip_grad_norm_` to clip the gradients during training.
# This can help prevent the gradients from becoming too large and causing the model to diverge.

# Use `torch.utils.tensorboard` to visualize the training process.
# This can help you track the progress of the model and identify any potential problems.


### PyTorch Tip - 3


**Using torch.where() for Conditional Element-wise Operations**
PyTorch's **torch.where()** function allows you to perform conditional element-wise operations efficiently. It takes three arguments: the condition, the tensor to select values from when the condition is true, and the tensor to select values from when the condition is false. This is particularly useful for implementing conditional logic within your neural network models.

Here's a quick example:
In this example, the elements from tensor_true are selected where the condition is True, and elements from tensor_false are selected where the condition is False. This allows for flexible conditional operations within your PyTorch code.

In [1]:
import torch

# Define tensors
condition = torch.tensor([[True, False], [False, True]])
tensor_true = torch.tensor([[1, 2], [3, 4]])
tensor_false = torch.tensor([[5, 6], [7, 8]])

# Perform conditional element-wise operation
result = torch.where(condition, tensor_true, tensor_false)
print(result)


tensor([[1, 6],
        [7, 4]])


**Some Practical usages below:**

**1. Masked Operations:** You might have a tensor and want to perform different operations on elements based on some condition. For instance, in natural language processing, you might want to mask out certain tokens during tokenization or in attention mechanisms based on some condition.

In [2]:
import torch

# Example: Masking tokens with a special token ID
input_ids = torch.tensor([101, 102, 103, 104, 105])  # Example input tensor
mask_condition = input_ids == 103  # Condition to mask out token with ID 103
special_token_id = 1000  # Special token ID to replace masked tokens

# Mask out tokens with ID 103
masked_input_ids = torch.where(mask_condition, torch.tensor(special_token_id), input_ids)

print(masked_input_ids)


tensor([ 101,  102, 1000,  104,  105])


**2. Loss Function Modification:** During training, you may want to apply different weights to different elements of the loss function based on some condition.

In [3]:
import torch.nn.functional as F

# Example: Modifying loss function based on class imbalance
predicted_scores = torch.tensor([0.1, 0.8, 0.3, 0.9, 0.2])  # Example predicted scores
true_labels = torch.tensor([0, 1, 0, 1, 1])  # Example true labels

# Calculate binary cross-entropy loss with class imbalance handling
positive_weight = 2.0  # Weight for positive class
negative_weight = 1.0  # Weight for negative class
loss_weights = torch.where(true_labels == 1, positive_weight, negative_weight)

# Calculate weighted binary cross-entropy loss
loss = F.binary_cross_entropy_with_logits(predicted_scores, true_labels.float(), weight=loss_weights)

print(loss)


tensor(0.8439)


**Model Interpretability:** In some scenarios, you might want to interpret the output of your model differently based on certain conditions.

In [4]:
import torch

# Example: Interpreting model output differently based on confidence
output_scores = torch.tensor([0.8, 0.6, 0.9, 0.4, 0.7])  # Example output scores
confidence_threshold = 0.7  # Threshold for high confidence

# Determine model predictions based on confidence
predictions = torch.where(output_scores >= confidence_threshold, torch.tensor(1), torch.tensor(0))

print(predictions)

tensor([1, 0, 1, 0, 1])
